import subprocess
import os

def test_mason_help_is_token_minimal():
    """
    Asserts that --help is natively generated by argparse to prevent drift,
    exits with 0, and avoids verbose generative steering vectors.
    """
    cmd = ["./bin/mason", "--help"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    assert result.returncode == 0
    assert "usage: mason" in result.stdout.lower()
    assert "validate" in result.stdout
    assert "install" in result.stdout

def test_mason_rejects_hallucinated_commands():
    """
    Asserts the Command Sovereignty Invariant. Fuzzy or hallucinated subcommands
    must be violently rejected with a native argparse error, not interpolated.
    """
    cmd = ["./bin/mason", "hallucinate"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    # argparse exits 2 on invalid usage
    assert result.returncode == 2
    assert "invalid choice: 'hallucinate'" in result.stderr.lower()


