import yaml
import os
import sys

# Attempt to load dip_sonar for validation, if not available just skip
try:
    from skills.dip_sonar import validate_matrix
except ImportError:
    validate_matrix = None

def compile_anchor():
    dip_path = "artifacts/dip_state.yml"
    target_path = "GEMINI.md"
    
    # 1. Validation
    if validate_matrix and os.path.exists(dip_path):
        try:
            validate_matrix(dip_path)
        except Exception as e:
            print(f"🚨 [ANCHOR COMPILER] dip_state.yml validation failed: {e}")
            sys.exit(1)
            
    # 2. Extract state
    approved_dimensions = {}
    if os.path.exists(dip_path):
        with open(dip_path, "r") as f:
            data = yaml.safe_load(f) or {}
            
        dimensions = data.get("dimensions", {})
        # Sort dimensions by their numerical index prefix
        def extract_idx(key):
            try:
                return int(key.split("_")[0])
            except:
                return 999
                
        sorted_dims = sorted(dimensions.items(), key=lambda x: extract_idx(x[0]))
        
        for k, v in sorted_dims:
            if v.get("status") == "APPROVED":
                # Convert `1_identity` to `1. Identity`
                title_parts = k.split("_", 1)
                if len(title_parts) == 2:
                    title = f"{title_parts[0]}. {title_parts[1].replace('_', ' ').title()}"
                else:
                    title = k.title()
                approved_dimensions[title] = v.get("content", "")
                
    targets = {
        "GEMINI.md": "Gemini",
        "CLAUDE.md": "Claude"
    }

    for target_path, ai_name in targets.items():
        out = []
        out.append(f"# dyad-cairn — {target_path}")
        out.append("")
        out.append("> ⚠️ **DO NOT EDIT THIS FILE DIRECTLY.**")
        out.append("> This is a Materialized View physically projected by `anchor_compiler.py` from `dip_state.yml`.")
        out.append("> Any manual changes here will be overwritten.")
        out.append("")
        out.append(f"> **This is the platform shim for {ai_name}.**")
        out.append("> You must load `DYAD.md` as the universal instruction layer for the dyad.")
        out.append("")
        out.append("**CRITICAL INSTRUCTION:** Read `DYAD.md` before proceeding.")
        out.append("")
        
        if approved_dimensions:
            out.append("---")
            out.append("")
            out.append("# Dyad Instantiation State")
            out.append("*The following parameters define the structural identity of this dyad.*")
            out.append("")
            for title, content in approved_dimensions.items():
                out.append(f"## {title}")
                out.append(str(content).strip())
                out.append("")
                
        with open(target_path, "w") as f:
            f.write("\n".join(out))
            
        print(f"[ANCHOR COMPILER] Materialized projection to {target_path} complete.")

if __name__ == "__main__":
    compile_anchor()
