import sys
import json
import datetime
import os

def get_state_dir(tool=None):
    dir_name = f"{tool}-state" if tool else "dyad-state"
    if os.environ.get("DYAD_TEST_ENV") == "true":
        return os.path.join("test_ledger", dir_name)
    return dir_name

def get_jsonl_file(tool=None):
    return os.path.join(get_state_dir(tool), "ledger.jsonl")

def get_md_file(tool=None):
    return f"{tool.upper()}_LEDGER.md" if tool else "DYAD_LEDGER.md"

def get_carry_forward_file():
    return os.path.join(get_state_dir(), "carry-forward.md")

def append_ledger(action: str, message: str, tool_name: str = None):
    state_dir = get_state_dir(tool_name)
    jsonl_file = get_jsonl_file(tool_name)
    md_file = get_md_file(tool_name)
    
    os.makedirs(state_dir, exist_ok=True)
    
    # 1. Append to the true machine ledger (JSONL)
    entry = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat() + "Z",
        "action": action.upper(),
        "message": message
    }
    import fcntl
    with open(jsonl_file, "a") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        f.write(json.dumps(entry) + "\n")
        fcntl.flock(f, fcntl.LOCK_UN)
        
    # 2. Regenerate the human-readable markdown ledger
    lines = []
    if os.path.exists(jsonl_file):
        with open(jsonl_file, "r") as f:
            for line in f:
                if line.strip():
                    try:
                        data = json.loads(line)
                        ts = data["timestamp"].split("T")[0] + " " + data["timestamp"].split("T")[1][:8]
                        formatted_message = data['message'].replace('\n', '\n  ')
                        lines.append(f"- **{ts}** | `{data['action']}` | {formatted_message}")
                    except Exception as e:
                        print(f"Error parsing line: {line}. {e}")
                    
    md_content = f"# dyad-cairn — {os.path.basename(md_file)}\n\n"
    if tool_name:
        md_content += f"> This is the append-only transaction log for `{tool_name}`.\n"
    else:
        md_content += "> This is the append-only transaction log for `dyad-cairn`'s un-anchored state.\n"
    md_content += "> **DO NOT EDIT THIS FILE DIRECTLY.** It is regenerated automatically by `./bin/pin` and `./bin/clip`.\n\n"
    md_content += "\n".join(lines) + "\n"
    
    with open(md_file, "w") as f:
        f.write(md_content)
    
    if action.lower() == "retro":
        pass
        
    print(f"[{action.upper()}] Successfully locked to ledger: {message}")

def append_carry_forward(note: str):
    """Single-home resume ledger, adopted from dyad-bond's carry-forward discipline
    (github.com/pltrinh1122/dyad-bond, dialectic/carry-forward.md). Read at SESSION_START;
    written by ./bin/d-reflect so the next session's resume has live in-flight state to read,
    since the Operator restarts fresh (SESSION_START) rather than resuming this conversation."""
    path = get_carry_forward_file()
    os.makedirs(os.path.dirname(path), exist_ok=True)

    if not os.path.exists(path):
        header = (
            "# dyad-cairn — Carry-Forward Ledger\n\n"
            "> Live in-flight state. Read this right after the anchor (`DYAD.md`, booted via the\n"
            "> `CLAUDE.md`/`GEMINI.md` shim) at SESSION_START to resume. Single home for open items;\n"
            "> close them here as they clear. Adopted from dyad-bond's carry-forward discipline\n"
            "> (`github.com/pltrinh1122/dyad-bond`), written by `./bin/d-reflect`.\n"
        )
        with open(path, "w") as f:
            f.write(header)

    ts = datetime.datetime.now(datetime.timezone.utc).isoformat() + "Z"
    with open(path, "a") as f:
        f.write(f"\n## {ts}\n\n{note}\n")

    print(f"[CARRY-FORWARD] Resume note appended to {path}.")


def process_retro(summary: str, file_path: str):
    os.makedirs("dyad-state", exist_ok=True)
    
    if file_path and os.path.exists(file_path):
        with open(file_path, "r") as f:
            payload = f.read()
        full_message = f"{summary}\n\n<details><summary>View Retro Payload</summary>\n\n{payload}\n</details>"
    else:
        payload = summary
        full_message = summary

    # 1. Sync Ledger
    append_ledger("retro", full_message)
    
    # 2. Outbox Sync (Fixing the vulnerability: syncing the full file, not just the summary)
    outbox_dir = "dm/dyad-touchstone"
    os.makedirs(outbox_dir, exist_ok=True)
    ts_clean = datetime.datetime.now(datetime.timezone.utc).isoformat().replace(":", "-").replace(".", "-") + "Z"
    outbox_file = os.path.join(outbox_dir, f"retro_{ts_clean}.md")
        
    with open(outbox_file, "w") as f:
        f.write(payload)
    print(f"[SYNC] Full CSS Retro payload physically routed to {outbox_file} for Touchstone.")
    
    # 3. Disarm the Lock
    lock_path = "dyad-state/RETRO_ACTIVE.lock"
    if os.path.exists(lock_path):
        os.remove(lock_path)
        print(f"[GUARDRAIL] Retro lock removed. SPAOR state machine unblocked.")
        
    # 4. Mechanical UI Presentation (CSI Guard for UI formatting)
    print("\n" + "="*80)
    print("📋 [MECHANICAL UI PRESENTATION: RETRO SUMMARY]")
    print(f"Summary: {summary}")
    print("="*80)
    if file_path and os.path.exists(file_path):
        print(payload)
    print("="*80)
    print("[CYBERNETIC STEERING VECTOR] The Engine is open. Re-enter the SPAOR loop at Step 1 (Sense).")
    print("-> Read artifacts/frontier_state.md and the active DAG to ingest the next constraints.\n")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("action", help="The ledger action (e.g., clip, retro, pin)")
    parser.add_argument("message", help="The message to log or the retro summary")
    parser.add_argument("file_path", nargs="?", help="Optional file path for retro")
    parser.add_argument("--tool", dest="tool_name", help="Target tool isolated ledger")
    args = parser.parse_args()
    
    if args.action.lower() == "retro":
        process_retro(args.message, args.file_path)
    elif args.action.lower() == "carry-forward":
        append_carry_forward(args.message)
    else:
        append_ledger(args.action, args.message, tool_name=args.tool_name)
