import sys
import json
import datetime
import os

JSONL_FILE = "dyad-state/ledger.jsonl"
MD_FILE = "DYAD_LEDGER.md"

def append_pin(message: str):
    os.makedirs("dyad-state", exist_ok=True)
    
    # 1. Append to the true machine ledger (JSONL)
    entry = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat() + "Z",
        "action": "PIN",
        "message": message
    }
    with open(JSONL_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")
        
    # 2. Regenerate the human-readable markdown ledger
    # Rebuilding it from the JSONL ensures the MD perfectly mirrors the strict log
    lines = []
    if os.path.exists(JSONL_FILE):
        with open(JSONL_FILE, "r") as f:
            for line in f:
                if line.strip():
                    data = json.loads(line)
                    # Use split to make the timestamp slightly more readable while preserving uniqueness
                    ts = data["timestamp"].split("T")[0] + " " + data["timestamp"].split("T")[1][:8]
                    lines.append(f"- **{ts}** | `{data['action']}` | {data['message']}")
                    
    md_content = "# dyad-cairn — DYAD_LEDGER.md\n\n"
    md_content += "> This is the append-only transaction log for `dyad-cairn`'s un-anchored state.\n"
    md_content += "> **DO NOT EDIT THIS FILE DIRECTLY.** It is regenerated automatically by `./bin/pin`.\n\n"
    md_content += "\n".join(lines) + "\n"
    
    with open(MD_FILE, "w") as f:
        f.write(md_content)
    
    print(f"[PIN] Successfully locked to ledger: {message}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 skills/pin_manager.py <message>")
        sys.exit(1)
    append_pin(sys.argv[1])
